[workspace]
members = [
  "futures",
  "futures-core",
  "futures-channel",
  "futures-executor",
  "futures-io",
  "futures-sink",
  "futures-util",
  "futures-test",
]

[patch.crates-io]
pin-utils = { git = "https://github.com/Kroisse/pin-utils.git", branch = "pin" }
